# Generated by Django 5.2.9 on 2025-12-29 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDevotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='devotions/')),
                ('citation', models.CharField(max_length=200)),
                ('verse_content', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hook', models.CharField(max_length=280)),
                ('personal_question', models.TextField()),
                ('biblical_qa', models.TextField()),
                ('reflection', models.TextField()),
                ('story', models.TextField()),
                ('prayer', models.TextField()),
                ('activity_guide', models.TextField()),
                ('date_posted', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_posted', '-created_at'],
            },
        ),
    ]
