# Generated by Django 5.2.9 on 2025-12-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydevotion',
            name='cover_image',
        ),
    ]
