# Generated by Django 5.2.9 on 2026-01-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0002_remove_dailydevotion_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypost',
            name='series_title',
            field=models.CharField(default='No Title', max_length=280),
        ),
        migrations.AddField(
            model_name='dailypost',
            name='theme',
            field=models.TextField(default='No Theme'),
        ),
    ]
