# Generated by Django 5.2.9 on 2026-01-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0003_dailypost_series_title_dailypost_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hymn_number', models.PositiveIntegerField(help_text='Numeric identifier for the hymn')),
                ('hymn_title', models.CharField(help_text='Title of the hymn', max_length=255)),
                ('classification', models.CharField(help_text='Hymn classification or category', max_length=100)),
                ('tune_ref', models.CharField(help_text='Tune reference for the hymn', max_length=100)),
                ('cross_ref', models.CharField(blank=True, help_text='Cross references to related hymns', max_length=255)),
                ('scripture', models.CharField(blank=True, help_text='Primary scripture reference', max_length=255)),
                ('chorus_title', models.CharField(blank=True, help_text='Title of the chorus (if applicable)', max_length=255)),
                ('chorus', models.TextField(blank=True, help_text='Chorus text')),
                ('verses', models.JSONField(blank=True, default=list, help_text='Ordered list of hymn verses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hymn_number'],
                'constraints': [models.UniqueConstraint(fields=('hymn_number',), name='unique_hymn_number')],
            },
        ),
    ]
