# Generated by Django 5.2.9 on 2026-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0004_hymn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hymn',
            options={'ordering': ['-hymn_number']},
        ),
        migrations.AddField(
            model_name='dailydevotion',
            name='prayer',
            field=models.TextField(default='Take a quiet moment here. Let this verse guide your own words before the Lord. Speak from your heart.'),
        ),
    ]
