# Generated by Django 5.2.9 on 2026-03-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0005_alter_hymn_options_dailydevotion_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='Title of the hymn', max_length=255)),
                ('sub_type', models.CharField(help_text='Hymn classification or category', max_length=100)),
                ('prayer', models.TextField(help_text='Text of the prayer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['type', 'sub_type'],
                'constraints': [models.UniqueConstraint(fields=('type',), name='unique_prayer_type')],
            },
        ),
    ]
