# Generated by Django 5.2.9 on 2026-03-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lodge', '0006_prayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the prayer type', max_length=255)),
                ('subtitle', models.CharField(help_text='Subtitle or description of the prayer type', max_length=255)),
                ('color_code', models.CharField(help_text='Color code for the prayer type', max_length=255)),
            ],
            options={
                'verbose_name': 'PrayerCategory',
                'verbose_name_plural': 'PrayerCategories',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='prayer',
            options={'ordering': ['type__title', 'sub_type']},
        ),
        migrations.RemoveConstraint(
            model_name='prayer',
            name='unique_prayer_type',
        ),
        migrations.AlterField(
            model_name='prayer',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prayers', to='lodge.prayercategory'),
        ),
    ]
